name: Update README

on:
  push:
    paths:
      - "openapi.yaml"
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install pyyaml

      - name: Generate README.md
        run: python generate_readme.py

      - name: Commit and push changes
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}  # Use the token from secrets
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}
          git add README.md
          git commit -m "Auto-update README.md from openapi.yaml" || echo "No changes to commit"
          git push origin main

